import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF3E2',
    paddingTop: 40,
    paddingHorizontal: 16,
  },
  titulo: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FF8C42',
    textAlign: 'center',
    marginBottom: 16,
  },
  subtitulo: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FF8C42',
    marginTop: 20,
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#FFD8B8',
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    marginBottom: 16,
    color: '#333',
  },
  botaoNovo: {
    backgroundColor: '#FF8C42',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 20,
  },
  textoBotao: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  cardProduto: {
    flex: 1,
    backgroundColor: '#FFD8B8',
    borderRadius: 12,
    margin: 5,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  imagemProduto: {
    width: 60,
    height: 60,
    borderRadius: 10,
    marginBottom: 8,
  },
  nomeProduto: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  precoProduto: {
    fontSize: 14,
    color: '#FF8C42',
    fontWeight: '600',
    marginTop: 4,
  },
  itemCarrinho: {
    backgroundColor: '#FFD8B8',
    borderRadius: 12,
    marginVertical: 6,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  infoItem: {
    flex: 1,
  },
  nomeItem: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  precoItem: {
    fontSize: 14,
    color: '#FF8C42',
    fontWeight: '600',
    marginTop: 2,
  },
  botaoRemover: {
    backgroundColor: '#FF6B6B',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  textoBotaoRemover: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  total: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FF8C42',
    textAlign: 'center',
    marginVertical: 20,
    padding: 16,
    backgroundColor: '#FFD8B8',
    borderRadius: 12,
  },
  botaoSalvar: {
    backgroundColor: '#FF8C42',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  botaoCancelar: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FF8C42',
  },
  textoBotaoCancelar: {
    color: '#FF8C42',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;